-- Where a queued report was addressed.
--
-- One column added rather than a table rebuilt, for the reason 004 gives:
-- `ALTER TABLE ADD COLUMN` leaves the existing rows' storage alone, so this
-- avoids the create-copy-drop-rename recipe and with it the foreign-key trap the
-- header of `migrations.rs` warns about.
--
-- Why this exists. `watch_deliveries` recorded the bytes and nothing about their
-- destination, and `due` had no destination predicate -- so the queue was drained
-- through whichever client the current invocation happened to build. Pointing the
-- monitor at a request bin to see what the payload looks like, which is the first
-- thing anybody does, therefore sent the reports queued for the team's receiver
-- to the request bin instead, with the team's bearer token on them, and marked
-- them delivered. Not only leaked: permanently lost for the address they were
-- made for.
--
-- The origin rather than the whole URL, because that is the unit a credential
-- belongs to: a path or a query that changed is the same receiver, a host that
-- changed is not.
--
-- NULL for the rows already in the table when this ran. They were queued before
-- anything recorded a destination, so nothing can say where they belong, and
-- `due` treats them as belonging wherever it is asked -- which is exactly the old
-- behavior, kept for those rows only rather than guessed at.
ALTER TABLE watch_deliveries ADD COLUMN destination TEXT;
