# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram from the terminal: who does not follow you back"
  homepage "https://github.com/dennisgr7/snob-ig"
  version "0.1.0"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.0/snob-v0.1.0-aarch64-apple-darwin.tar.gz"
    sha256 "d7e2950d4eb7abd632701b7b1b08949f7de9a38e3f4260dcf60ca6a945ba26bb"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.0/snob-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ebaa1367d4f52a59ee6549f726979bf7b13604659d8f3e76045a16adc9611887"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.0/snob-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "193a099e8fc9a85cd020a1fabb0e38c3e0b0b52eddb727e7daf35c4f4e32299c"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and a browser profile outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
