# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram from the terminal: who does not follow you back"
  homepage "https://github.com/dennisgr7/snob-ig"
  version "0.5.0"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-ig/releases/download/v0.5.0/snob-v0.5.0-aarch64-apple-darwin.tar.gz"
    sha256 "b5cebfd61c12d10dd2007b149c84c5bf4878b8cbf039c37f55e4dc12f012e267"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.5.0/snob-v0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "30b6f8f3b794316716ef48b814ddebf4f643c521a41d00f6252251948ad0faf2"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.5.0/snob-v0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e7b02f669d9a2e1a277cef862f5a07fa9cc7f79d8d41fecae1e77b2926a26fb7"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and a browser profile outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
