# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram from the terminal: who does not follow you back"
  homepage "https://github.com/dennisgr7/snob-ig"
  version "0.1.1"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.1/snob-v0.1.1-aarch64-apple-darwin.tar.gz"
    sha256 "5d8cb6100b6accc8a913e4276742e4acd69fb8c1f058d0928e50c2feb8bd34e9"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.1/snob-v0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "5951e4e912437f02a87b3639de9e7d16de4428ec4ef14e05fde8ea0fbf62150c"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-ig/releases/download/v0.1.1/snob-v0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c49d9f38dbed161f81139167d8eb5a1965cd3ee3041062b3d0d78253a103295b"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and a browser profile outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
