#!/usr/bin/env bash
#
# Writes the Homebrew formula and the Scoop manifest for a released version.
#
# One generator rather than two files kept in step by hand: a formula whose
# checksum belongs to a different release fails at install time with a message
# about a corrupt download, which is the least informative way to find out.
#
#     packaging/render.sh 0.1.0 path/to/SHA256SUMS
#
# The same script runs from the release workflow, so what is committed here is
# always what the workflow would have produced.

set -euo pipefail

version="${1:?usage: render.sh VERSION SHA256SUMS}"
sums="${2:?usage: render.sh VERSION SHA256SUMS}"

repo="https://github.com/dennisgr7/snob-ig"
base="$repo/releases/download/v$version"

# The checksum for one archive, by target.
sum() {
  local target="$1" ext="$2"
  local line
  line=$(grep "snob-v$version-$target.$ext\$" "$sums") || {
    echo "no checksum for $target.$ext in $sums" >&2
    exit 1
  }
  echo "$line" | awk '{print $1}'
}

mac_arm=$(sum aarch64-apple-darwin tar.gz)
linux_x86=$(sum x86_64-unknown-linux-musl tar.gz)
linux_arm=$(sum aarch64-unknown-linux-musl tar.gz)
win_x86=$(sum x86_64-pc-windows-msvc zip)
win_arm=$(sum aarch64-pc-windows-msvc zip)

mkdir -p Formula bucket

# --- Homebrew ------------------------------------------------------------
#
# A tap does not have to be a repository of its own: `brew tap <name> <url>`
# takes any repository, so this lives beside the code it describes and is
# updated by the same workflow that publishes the release. That is what keeps
# it from needing a token for somewhere else.
cat > Formula/snob.rb <<EOF
# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram from the terminal: who does not follow you back"
  homepage "$repo"
  version "$version"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "$base/snob-v$version-aarch64-apple-darwin.tar.gz"
    sha256 "$mac_arm"
  end

  on_linux do
    on_intel do
      url "$base/snob-v$version-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "$base/snob-v$version-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and a browser profile outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
EOF

# --- Scoop ---------------------------------------------------------------
#
# checkver and autoupdate let Scoop's own tooling follow new releases without
# this repository telling it to, and the hashes come from the SHA256SUMS file
# the release already publishes rather than being recomputed by anybody.
cat > bucket/snob.json <<EOF
{
    "version": "$version",
    "description": "Instagram from the terminal: who does not follow you back",
    "homepage": "$repo",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "$base/snob-v$version-x86_64-pc-windows-msvc.zip",
            "hash": "$win_x86",
            "extract_dir": "snob-v$version-x86_64-pc-windows-msvc"
        },
        "arm64": {
            "url": "$base/snob-v$version-aarch64-pc-windows-msvc.zip",
            "hash": "$win_arm",
            "extract_dir": "snob-v$version-aarch64-pc-windows-msvc"
        }
    },
    "bin": "snob.exe",
    "notes": [
        "snob keeps a session, a database and a browser profile outside this",
        "directory, which uninstalling cannot reach. Run \\"snob purge\\" before",
        "removing it to take those off the machine too."
    ],
    "checkver": {
        "github": "$repo"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "$repo/releases/download/v\$version/snob-v\$version-x86_64-pc-windows-msvc.zip",
                "extract_dir": "snob-v\$version-x86_64-pc-windows-msvc"
            },
            "arm64": {
                "url": "$repo/releases/download/v\$version/snob-v\$version-aarch64-pc-windows-msvc.zip",
                "extract_dir": "snob-v\$version-aarch64-pc-windows-msvc"
            }
        },
        "hash": {
            "url": "$repo/releases/download/v\$version/SHA256SUMS"
        }
    }
}
EOF

# --- WinGet --------------------------------------------------------------
#
# Unlike the other two, these are not read from here: they have to be sent as
# a pull request to microsoft/winget-pkgs, which is a repository this project
# does not control. They are generated anyway so that the submission is a copy
# rather than a retyping, and so a version bump cannot leave them behind.
#
# The archive holds the executable inside a directory, which is what makes this
# a zip installer with a nested portable rather than a portable one. WinGet
# wants its checksums in upper case.
mkdir -p packaging/winget
release_date=$(date -u +%F)

cat > packaging/winget/dennisgr7.snob.yaml <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: dennisgr7.snob
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > packaging/winget/dennisgr7.snob.installer.yaml <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: dennisgr7.snob
PackageVersion: $version
InstallerType: zip
NestedInstallerType: portable
Commands:
  - snob
ReleaseDate: $release_date
Installers:
  - Architecture: x64
    InstallerUrl: $base/snob-v$version-x86_64-pc-windows-msvc.zip
    InstallerSha256: $(echo "$win_x86" | tr '[:lower:]' '[:upper:]')
    NestedInstallerFiles:
      - RelativeFilePath: snob-v$version-x86_64-pc-windows-msvc\\snob.exe
        PortableCommandAlias: snob
  - Architecture: arm64
    InstallerUrl: $base/snob-v$version-aarch64-pc-windows-msvc.zip
    InstallerSha256: $(echo "$win_arm" | tr '[:lower:]' '[:upper:]')
    NestedInstallerFiles:
      - RelativeFilePath: snob-v$version-aarch64-pc-windows-msvc\\snob.exe
        PortableCommandAlias: snob
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > packaging/winget/dennisgr7.snob.locale.en-US.yaml <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: dennisgr7.snob
PackageVersion: $version
PackageLocale: en-US
Publisher: dennisgr7
PublisherUrl: https://github.com/dennisgr7
PackageName: snob
PackageUrl: $repo
License: MIT
LicenseUrl: $repo/blob/main/LICENSE
ShortDescription: "Instagram from the terminal: who does not follow you back"
Description: |-
  Walks an Instagram account's followers and following, crosses them, and
  reports who does not follow you back, who you never followed back, and who
  you and somebody else both know. It reads only: it never follows, unfollows,
  blocks or removes anyone.
Tags:
  - instagram
  - cli
  - followers
  - unfollowers
ReleaseNotesUrl: $repo/releases/tag/v$version
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

echo "wrote Formula/snob.rb, bucket/snob.json and packaging/winget/ for $version"
